query($cate: ColorCategory!) {
  color(category: $cate) {
    id
    like
    color
    userid
    username
    createdate
  }
}

{
  "cate": "PUBLIC" // "ANONYMOUS"
}

mutation($val: LikeColorInputType!) {
  adjudicateColor(input: $val) {
    data
    error
  }
}

mutation($val: LikeColorInputType!) {
  likeColor(input: $val) {
    data
    error
  }
}

{
  "val": {
    "id": 1,
    "willLike": true
  }
}
